apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: 'cloudflare-staging'
spec:
  acme:
    email: myemail@mydomain.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: 'cloudflare-staging-account-key'
    solvers:
      - dns01:
          cloudflare:
            email: myemail@mydomain.com
            apiTokenSecretRef:
              name: cloudflare
              key: cloudflare-api-token
